/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progressive;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class prog3 extends javax.swing.JFrame {
 static final String url = "jdbc:mysql://localhost:3306/duplic";
    static final String driver = "com.mysql.jdbc.Driver";
    static final String user = "root";
    static final String passw = "root";
    int t[]=new int[1000];
    String u[]=new String[1000];
    String v[]=new String[1000];
    String x[]=new String[1000];
    String a[]=new String[1000];
    String w[]=new String[1000];
    String l[]=new String[1000];
    String kl[]=new String[1000];
    Double se1[]=new Double[1000];
    Double se2[]=new Double[1000];
    Double se3[]=new Double[1000];
    Double se4[]=new Double[1000];
    //private double Integer;
    /**
     * Creates new form prog3
     */
    public prog3() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(618, 624));
        setMinimumSize(new java.awt.Dimension(618, 624));
        setPreferredSize(new java.awt.Dimension(618, 624));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jComboBox1.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Select---", "american", "californian", "french", "asian", "japanese", "seafood", "italian", "continental", "indian", "pakistani", "caribbean", "mexican", "steakhouses" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(70, 120, 120, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 170, 300, 330);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(20, 530, 140, 30);

        jButton1.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jButton1.setText("Get Count1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 530, 130, 30);

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel1.setText("Avg type for user (Onj)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 490, 180, 40);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(320, 170, 290, 330);

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel2.setText("Avg type for user2 (Omj)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 500, 180, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(320, 530, 150, 30);

        jButton2.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jButton2.setText("Get Count2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(480, 530, 120, 30);

        jComboBox3.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Select---", "american", "californian", "french", "asian", "japanese", "seafood", "italian", "continental", "indian", "pakistani", "caribbean", "mexican", "steakhouses" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(400, 120, 120, 30);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel3.setText("Progressive Duplicate Detection");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 10, 600, 90);

        jButton3.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jButton3.setText("Next");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(270, 563, 110, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progressive/abstract2.jpg"))); // NOI18N
        jLabel4.setText("jLabel2");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 620, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
          try{
            int i=0;
            Connection con = null;
            Statement stmt = null;
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(url, user, passw);
            stmt =(Statement) con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from dup");
             while(rs.next())
             {
                 t[i]=rs.getInt("id");
                 u[i]=rs.getString("name");
                 v[i]=rs.getString("address");
                 x[i]=rs.getString("city");
                 a[i]=rs.getString("phone");
                 w[i]=rs.getString("type");
                 l[i]=rs.getString("class1");
                 i++;
             }
           DefaultTableModel model=new DefaultTableModel();
           jTable1.setModel(model);
           model.addColumn("id");
           model.addColumn("address");
           model.addColumn("city");
            model.addColumn("type");
             String str=(String)jComboBox1.getSelectedItem();
             for(int j=0;j<i;j++)
             {
              if(str.equals(w[j]))
              {
                 model.addRow(new Object[] {t[j],u[j],v[j],w[j]});
              }
             }        
           }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            try{
            int i=0;
            Connection con = null;
            Statement stmt = null;
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(url, user, passw);
            stmt =(Statement) con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from dup");
            while(rs.next())
            {
                t[i]=rs.getInt("id");
                u[i]=rs.getString("name");
                v[i]=rs.getString("address");
                x[i]=rs.getString("city");
                a[i]=rs.getString("phone");
                w[i]=rs.getString("type");
                l[i]=rs.getString("class1");
                i++;
            }
           int c=0,d=0;
             String str=(String)jComboBox1.getSelectedItem();
             for(int j=0;j<i;j++)
             { 
                 if(/*str2.equals(t[j]) &&*/ str.equals(w[j]))
                 {
                  c++;
                 }
             }
             jTextField1.setText(Integer.toString(c));
//      
            }
          catch(Exception e)
          {
              System.out.println(e.getMessage());
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          try{
            int i=0;
            Connection con = null;
            Statement stmt = null;
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(url, user, passw);
            stmt =(Statement) con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from dup");
            while(rs.next())
            {
                t[i]=rs.getInt("id");
                u[i]=rs.getString("name");
                v[i]=rs.getString("address");
                x[i]=rs.getString("city");
                a[i]=rs.getString("phone");
                w[i]=rs.getString("type");
                l[i]=rs.getString("class1");
                i++;
            }
           int c=0,d=0;
             String str=(String)jComboBox1.getSelectedItem();
             String str1=(String)jComboBox3.getSelectedItem();
             // String str2=(String)jComboBox3.getSelectedItem();
             for(int j=0;j<i;j++)
             { 
                 if( str1.equals(w[j]))
                 {
                  c++;
                 }
             }
             jTextField2.setText(Integer.toString(c));
            }
          catch(Exception e)
          {
              System.out.println(e.getMessage());
          }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
         try{
            int i=0;
            Connection con = null;
            Statement stmt = null;
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(url, user, passw);
            stmt =(Statement) con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from dup");
             while(rs.next())
             {
                 t[i]=rs.getInt("id");
                 u[i]=rs.getString("name");
                 v[i]=rs.getString("address");
                 x[i]=rs.getString("city");
                 a[i]=rs.getString("phone");
                 w[i]=rs.getString("type");
                 l[i]=rs.getString("class1");
                 i++;
             }
           DefaultTableModel model=new DefaultTableModel();
           jTable2.setModel(model);
           model.addColumn("id");
           model.addColumn("address");
           model.addColumn("city");
            model.addColumn("type");
          // model.addColumn("Landscape");
           //model.addColumn("season");
             String str=(String)jComboBox3.getSelectedItem();
             // String str1=(String)jComboBox2.getSelectedItem();
             for(int j=0;j<i;j++)
             {
              if(str.equals(w[j]))
              {
                 model.addRow(new Object[] {t[j],u[j],v[j],w[j]});
              }
             }
             
           }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new prog4().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prog3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prog3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prog3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prog3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prog3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
